#!/bin/bash
#
# setup.sh — install the OTP autofill daemon as a LaunchAgent.
#
# Builds a small app bundle around a private copy of the Python interpreter so
# that Full Disk Access can be granted to *this tool* rather than to your whole
# Python installation. Safe to re-run; it is idempotent.
#
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP="$HOME/Applications/OTP Autofill.app"
EXEC_NAME="OTP Autofill"
LABEL="com.kyra.otp-autofill"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
CONFIG_DIR="$HOME/.config/otp-autofill"
CONFIG="$CONFIG_DIR/config.json"
WATCHER="$REPO/daemon/otp_watcher.py"
PORT="${OTP_PORT:-8787}"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
info() { printf '  %s\n' "$*"; }

[ -f "$WATCHER" ] || { echo "error: $WATCHER not found"; exit 1; }

# --- 1. token -----------------------------------------------------------------
bold "1. Shared token"
if [ -f "$CONFIG" ] && /usr/bin/python3 -c "import json,sys;sys.exit(0 if json.load(open('$CONFIG')).get('token') else 1)" 2>/dev/null; then
  TOKEN="$(/usr/bin/python3 -c "import json;print(json.load(open('$CONFIG'))['token'])")"
  PORT="$(/usr/bin/python3 -c "import json;print(json.load(open('$CONFIG')).get('port',$PORT))")"
  info "reusing existing token from $CONFIG"
else
  TOKEN="$(/usr/bin/python3 -c 'import secrets;print(secrets.token_urlsafe(32))')"
  info "generated a new token"
fi

mkdir -p "$CONFIG_DIR"
cat > "$CONFIG" <<JSON
{
  "port": $PORT,
  "token": "$TOKEN",
  "ttl_seconds": 300,
  "poll_seconds": 1.5,
  "clipboard": true,
  "notify": true
}
JSON
chmod 700 "$CONFIG_DIR"
chmod 600 "$CONFIG"
info "wrote $CONFIG (0600)"

# --- 2. seed the extension with the same token --------------------------------
bold "2. Extension config"
cat > "$REPO/extension/config.js" <<JS
// GENERATED by setup.sh — do not edit by hand, and do not commit.
// Seeds chrome.storage on first install so there is no token to copy manually.
export const SEED = {
  port: $PORT,
  token: "$TOKEN",
};
JS
info "wrote extension/config.js"

# --- 3. app bundle around a private interpreter -------------------------------
bold "3. App bundle"
STAGING="$(mktemp -d)"
trap 'rm -rf "$STAGING"' EXIT

python3 -m venv --copies "$STAGING/venv" >/dev/null
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS"
cp "$STAGING/venv/bin/python3" "$APP/Contents/MacOS/$EXEC_NAME"

# The interpreter finds its stdlib via pyvenv.cfg, but codesign refuses to sign
# a bundle with a stray non-code file in Contents/. PYTHONHOME in the LaunchAgent
# does the same job and keeps the bundle cleanly signable.
# Prefer the version-independent opt/ symlink so a brew patch upgrade of Python
# does not break the path.
PYHOME="$(python3 - <<'PY'
import os, re, sys
base = sys.base_prefix
m = re.match(r"^(/opt/homebrew|/usr/local)/Cellar/(python@[\d.]+)/[^/]+/(Frameworks/.*)$", base)
if m:
    alt = f"{m.group(1)}/opt/{m.group(2)}/{m.group(3)}"
    if os.path.isdir(alt):
        base = alt
print(base)
PY
)"
info "PYTHONHOME=$PYHOME"

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleName</key><string>OTP Autofill</string>
  <key>CFBundleDisplayName</key><string>OTP Autofill</string>
  <key>CFBundleIdentifier</key><string>com.kyra.otp-autofill</string>
  <key>CFBundleExecutable</key><string>OTP Autofill</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>1.0.0</string>
  <key>CFBundleVersion</key><string>1.0.0</string>
  <key>LSUIElement</key><true/>
</dict></plist>
PLIST

codesign --force --sign - "$APP"
info "built and ad-hoc signed $APP"

if ! PYTHONHOME="$PYHOME" "$APP/Contents/MacOS/$EXEC_NAME" \
      -c 'import sqlite3, http.server' 2>/dev/null; then
  echo "error: bundled interpreter cannot load the stdlib with PYTHONHOME=$PYHOME"
  exit 1
fi
info "interpreter self-check passed"

# --- 4. LaunchAgent -----------------------------------------------------------
bold "4. LaunchAgent"
mkdir -p "$HOME/Library/LaunchAgents"
cat > "$PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$APP/Contents/MacOS/$EXEC_NAME</string>
    <string>$WATCHER</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PYTHONHOME</key><string>$PYHOME</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><dict><key>SuccessfulExit</key><false/></dict>
  <key>ThrottleInterval</key><integer>10</integer>
  <key>ProcessType</key><string>Background</string>
  <key>StandardOutPath</key><string>$HOME/Library/Logs/otp-autofill.out.log</string>
  <key>StandardErrorPath</key><string>$HOME/Library/Logs/otp-autofill.err.log</string>
</dict></plist>
PLIST

launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST"
info "loaded $LABEL"

# --- 5. next steps ------------------------------------------------------------
echo
bold "Done. Two manual steps remain:"
echo
echo "  A. Grant Full Disk Access (required to read Messages):"
echo "     System Settings → Privacy & Security → Full Disk Access → +"
echo "     Choose:  $APP"
echo "     Then:    launchctl kickstart -k gui/$(id -u)/$LABEL"
echo
echo "  B. Load the Chrome extension:"
echo "     chrome://extensions → enable Developer mode → Load unpacked"
echo "     Choose:  $REPO/extension"
echo
echo "  Verify with:  $REPO/daemon/otp_watcher.py --check"
echo "  Logs:         ~/Library/Logs/otp-autofill.log"
